server:
  port: 8888
spring:
  kafka:
    bootstrap-servers: linux:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432